# Generated by Django 5.1.6 on 2025-02-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oreder_status',
            new_name='order_status',
        ),
    ]
